version: "3"
services:
  nginx:
    build: ./server_configs/
    container_name: ecommerce-nginx 
    ports:   
      - 8080:80
    links:
      - php
    volumes_from:
      - php  
  php:
    build: ./server_configs/php/
    container_name: ecommerce
    expose:
      - 9000
    volumes:
      - ${PATH_TO_PROJECT_DIR}:/var/www/html/
    links:
      - mysql
  mysql:
    image: mysql:latest
    container_name: ecommerce-mysql
    restart: always
    volumes:
      - /var/lib/mysql
      - ./install/dev_ecommerce.sql:/docker-entrypoint-initdb.d/dev_ecommerce.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3307:3306